<style>
.bg_btn{
    background-color: #F6F6F6;
    border-bottom: 5px solid #555555;
    border-top: 5px solid #555555;
    margin-top: 20px;
    padding: 8px 10px;
    text-align: right;
}
</style>
<?php
echo $this->headLink()->prependStylesheet('/assets/css/coupon.css');

//FIRST COLUMN
$name            = $this->otucouponaddform->getElement('name');
$type            = $this->otucouponaddform->getElement('type');
$discountVal     = $this->otucouponaddform->getElement('discountVal');
$amountQualifier = $this->otucouponaddform->getElement('amountQualifier');
$ceilingAmount   = $this->otucouponaddform->getElement('ceilingAmount');
$plus            = $this->otucouponaddform->getElement('plus');
$minus           = $this->otucouponaddform->getElement('minus');
$hidden          = $this->otucouponaddform->getElement('last_coupon_field_id');
//END OF FIRST COLUMN

//SECOND COLUMN
$class           = $this->otucouponaddform->getElement('class');
$siteId          = $this->otucouponaddform->getElement('siteId');
$couponAppliesTo = $this->otucouponaddform->getElement('couponAppliesTo');
//END OF SECOND COLUMN

//THIRD COLUMN
$owner = $this->otucouponaddform->getElement('owner');
//END OF THIRD COLUMN

//FOURTH COLUMN
$appeasement = $this->otucouponaddform->getElement('appeasement');
//END OF FOURTH COLUMN

//FIFTH COLUMN
$startDate = $this->otucouponaddform->getElement('startDate');
$endDate   = $this->otucouponaddform->getElement('endDate');
//END OF FIFTH COLUMN

//SEVENTH COLUMN
$initialQuantity = $this->otucouponaddform->getElement('initialQuantity');
//END OF SEVENTH COLUMN

//EIGHTH COLUMN
$enabledisable_restrictions = $this->otucouponaddform->getElement('enabledisable_restrictions');
$restrictions               = $this->otucouponaddform->getElement('restrictions');
//END OF EIGHTH COLUMN

//NINETH COLUMN
$publish = $this->otucouponaddform->getElement('publish');
//END OF NINETH COLUMN

//BUTTONS
$cancel     = $this->otucouponaddform->getElement('cancel');
$coupon_add = $this->otucouponaddform->getElement('coupon_add');
//END OF BUTTONS

$description = $this->otucouponaddform->getElement('description');
$generate = $this->otucouponaddform->getElement('generate');

# Name: Del # Date Modify: April, 2015 #Start
$lowerLimit = $this->otucouponaddform->getElement('lowerLimit');
$dispense = $this->otucouponaddform->getElement('dispense');
$gated = $this->otucouponaddform->getElement('gated');
# Name: Del # Date Modify: April, 2015 #End

?>
<script type="text/javascript">
if(typeof String.prototype.trim !== 'function') {   String.prototype.trim = function() {     return this.replace(/^\s+|\s+$/g, '');    } }
var coupon_name = {};
coupon_name.id = "<?php echo $name->getId(); ?>";
coupon_name.label = "<?php echo $name->getLabel(); ?>";

var type = {};
type.id = "<?php echo $type->getId(); ?>";
type.label = "<?php echo $type->getLabel(); ?>";

var discountVal = {};
discountVal.id = "<?php echo $discountVal->getId(); ?>";
discountVal.label = "<?php echo $discountVal->getLabel(); ?>";

var amountQualifier = {};
amountQualifier.id = "<?php echo $amountQualifier->getId(); ?>";
amountQualifier.label = "<?php echo $amountQualifier->getLabel(); ?>";

var ceilingAmount = {};
ceilingAmount.id = "<?php echo $ceilingAmount->getId(); ?>";
ceilingAmount.label = "<?php echo $ceilingAmount->getLabel(); ?>";

var siteId = {};
siteId.id = "<?php echo $siteId->getId(); ?>";
siteId.label = "<?php echo $siteId->getLabel(); ?>";

var startDate = {};
startDate.id = "<?php echo $startDate->getId(); ?>";
startDate.label = "<?php echo $startDate->getLabel(); ?>";

var endDate = {};
endDate.id = "<?php echo $endDate->getId(); ?>";
endDate.label = "<?php echo $endDate->getLabel(); ?>";

var initialQuantity = {};
initialQuantity.id = "<?php echo $initialQuantity->getId(); ?>";
initialQuantity.label = "<?php echo $initialQuantity->getLabel(); ?>";

var description = {};
description.id = "<?php echo $description->getId(); ?>";
description.label = "<?php echo $description->getLabel(); ?>";

var generate = {};
generate.id = "<?php echo $generate->getId(); ?>";
generate.label = "<?php echo $generate->getLabel(); ?>";

var publish = {};
publish.id = "<?php echo $publish->getId(); ?>";
publish.label = "<?php echo $publish->getLabel(); ?>";

// # Name: Del # Date Modify: April 2016 #Start
var lowerLimit = {};
lowerLimit.id = "<?php echo $lowerLimit->getId(); ?>";
lowerLimit.label = "<?php echo $lowerLimit->getLabel(); ?>";

var dispense = {};
dispense.id = "<?php echo $dispense->getId(); ?>";
dispense.label = "<?php echo $dispense->getLabel(); ?>";

var gated = {};
gated.id = "<?php echo $gated->getId(); ?>";
gated.label = "<?php echo $gated->getLabel(); ?>";
// # Name: Del # Date Modify: April 2016 #End

var oneTimeUseLimit = parseInt(<?php echo $this->oneTimeUseLimit; ?>);

var errorHandler = {};
    errorHandler.NOT_EMPTY = "should not be empty";
    errorHandler.NUMBER_NOT_GREATER_THAN = "should not be greater than";
    errorHandler.INVALID_DAY_OF_MONTH = "Invalid day for the selected month: ";
    errorHandler.NUMBER_NOT_EQUAL = "should not be equal";
    errorHandler.IS_NUMERIC = "should be numeric";
    errorHandler.INVALID_DATE_END_AHEAD_OF_START = "Start date should not be ahead of End date";
    errorHandler.INVALID_DATE_NOT_EQUAL = "Dates should not be equal";
    errorHandler.COUPON_EXISTS = "Coupon with this name already exists";
	errorHandler.INVALID_CHAR = "Special Chars not allowed";
	errorHandler.NOT_ZERO = "Should not be 0 (zero)";
	errorHandler.PERCENT_NOT_GREATER_THAN = "should not be greater than 100";
	errorHandler.CEILING_GREATER_THAN_VALUES = "Ceiling should be greater than or equal the discount values";
	errorHandler.VALUES_LESS_THAN_CEILING = "Discount values should not be greater than the ceiling";
	errorHandler.WORKER_UNAVAILABLE = "Could not create coupon more than " + oneTimeUseLimit + " as the system is currently generating a large number of One Time Use Coupons for Batch: ";
	
	errorHandler.VALUE_LESS_THAN_QUALIFIER = "VALUE should not be greater than the qualifier";
	errorHandler.VALUE_QUALIFIER_NOT_SAME = "Value qualifier/s inputted should not be the same";
	errorHandler.DESCRIPTION_LESS_THAN_MIN = "Description should not be less than 15 characters";
	errorHandler.GENERATE_BEFORE_PUBLISH = "Generate this batch before you can publish";

	// # Name: Del # Date Modify: April 2016 #Start
	errorHandler.LOWER_LIMIT_GREATER_THAN_NUMBER_OF_COUPONS = "Must not be greater than the number of coupons";
	// # Name: Del # Date Modify: April 2016 #End

var intRegex = /^\d+$/;
var floatRegex = /^((\d+(\.\d *)?)|((\d*\.)?\d+))$/;
var specialCharRegex = /^[a-z0-9-]*$/i;
var descriptionMin = 15;
function validateForm(){
	try{
	    var countError = 0; 
	    
	    countError += checkIfEmpty(coupon_name);
	   
	    var descriptionInput = document.getElementById(description.id);
	//    descriptionInput.value = removeLeadingZero(descriptionInput.value);
	    var descriptEmptyChecker = checkIfEmpty(description);
	    if(descriptEmptyChecker == 0){
	        var descriptionValue = descriptionInput.value;
	        if(descriptionValue.length < descriptionMin){
	            showError(description,errorHandler.DESCRIPTION_LESS_THAN_MIN);
	            countError++;
	        }else{
	            removeError(description);
	        } 
	    }else{
	        countError++;
	    }
	       
	    
		var inputNameValue = $("#"+coupon_name.id).val();
	    if(countError<=0){
	        countError = hasCoupon();
	    }
		
		if(!specialCharRegex.test(inputNameValue) && countError<=0) {
			$('#'+coupon_name.id).addClass('errorFocus');
	        $('.'+coupon_name.id).html(name.label + " " + errorHandler.INVALID_CHAR);
			countError++;
		}
		
		var inputErrorCounter = 0;
	           /* $("#"+discountVal.id+", #"+amountQualifier.id+", #"+ceilingAmount.id).each(function(){
					var thisValue = this.value.trim();
					var countFailed = 0;
	                if(thisValue == ""){
	                    showError(this,errorHandler.NOT_EMPTY);
	                    inputErrorCounter++;
						countFailed++;
	                }else if(!isInt(thisValue)) {
	                    showError(this,errorHandler.IS_NUMERIC);
	                    inputErrorCounter++;
						countFailed++;
	                }else if(this.id == discountVal.id){
						if(document.getElementById('type').value == "percent" && parseInt(thisValue) > 100){
							showError(this,errorHandler.PERCENT_NOT_GREATER_THAN);
							inputErrorCounter++;
							countFailed++;
						}else if(parseInt(thisValue) > parseInt(document.getElementById(ceilingAmount.id).value)){
							showError(this,errorHandler.VALUES_LESS_THAN_CEILING);
							inputErrorCounter++;
							countFailed++;
						}else if(parseInt(thisValue) == 0){
							showError(this,errorHandler.NOT_ZERO);
							inputErrorCounter++;
							countFailed++;
						}
					}else if(this.id == ceilingAmount.id && parseInt(thisValue) == 0){
						showError(this,errorHandler.NOT_ZERO);
						inputErrorCounter++;
						countFailed++;
					}else{
						removeError(this);
					}
	            });
				
				countError += inputErrorCounter;*/
		
	     
	    var valueCounter = 0;
	    $('input[name^="'+discountVal.id+'"]').each(function(){
			this.value = removeLeadingZero(this.value);
	        var inputValue = this.value.trim();
	        if(inputValue == ""){
	            $(this).addClass('errorFocus');
	            showError(this,errorHandler.NOT_EMPTY);
	            countError++;
	            valueCounter++;
	        }else if(!intRegex.test(inputValue) || !floatRegex.test(inputValue)) {
	            showError(this,errorHandler.IS_NUMERIC);
	            countError++;
	            valueCounter++;
	        }else if(document.getElementById('type').value == "percent" && parseInt(inputValue) > 100){
				showError(this,errorHandler.PERCENT_NOT_GREATER_THAN);
				countError++;
				valueCounter++;
			}/*else if(document.getElementById('type').value == "percent" && parseInt(inputValue) > parseInt(document.getElementById(ceilingAmount.id).value)){
				showError(this,errorHandler.VALUES_LESS_THAN_CEILING);
				countError++;
				valueCounter++;
			}*/else if(parseInt(inputValue) == 0){
				showError(this,errorHandler.NOT_ZERO);
				countError++;
				valueCounter++;
			}else{
	            if(valueCounter==0){
					removeError(this);
	            }
	        }
	        countError += valueCounter;
	    });
	    
	    var qualifierCounter = 0;
	    $('input[name^="'+amountQualifier.id+'"]').each(function(){
			this.value = removeLeadingZero(this.value);
	        var inputValue = this.value.trim();
	        if(inputValue == ""){
	            showError(this,errorHandler.NOT_EMPTY);
	            countError++;
	            qualifierCounter++;
	        }else if(!isInt(inputValue)) {
	            showError(this,errorHandler.IS_NUMERIC);
	            countError++;
	            qualifierCounter++;
	        }else{
	            if(qualifierCounter==0){
	                removeError(this);
	            }
	        }
	        countError += qualifierCounter;
	    });
	        
	    var ceilingAmountCounter = 0;
		document.getElementById(ceilingAmount.id).value = removeLeadingZero(document.getElementById(ceilingAmount.id).value);
		var ceilingElement = document.getElementById(ceilingAmount.id);
		var ceilingValue = ceilingElement.value.trim();
			if(ceilingValue == ""){
				showError(ceilingElement,errorHandler.NOT_EMPTY);
	            countError++;
	            ceilingAmountCounter++;
			}else if(!isInt(ceilingValue)){
				showError(ceilingElement,errorHandler.IS_NUMERIC);
	            countError++;
				ceilingAmountCounter++;
			}else if(parseInt(ceilingValue) == 0){
				showError(ceilingElement,errorHandler.NOT_ZERO);
				countError++;
				ceilingAmountCounter++;
			}else{
				removeError(ceilingElement);
			}
		
		//ticket #343 - able to input multiple value qualifier with same values 
		//gconstantino 11/13/2012
		//start
				var valueElement = document.getElementsByName(discountVal.id+"[]");
				var qualifierElement = document.getElementsByName(amountQualifier.id+"[]");
				
				if(document.getElementById('type').value == "dollar" && (parseInt(valueElement[0].value) > parseInt(qualifierElement[0].value))){
					showError(discountVal,errorHandler.VALUE_LESS_THAN_QUALIFIER);
					countError++;
				}else{
					if(qualifierCounter==0 && valueCounter==0 && valueElement.length > 1){
						var valueQualifierElement = [];
						
						var sameValueQualifierErrorCounter = 0;
						var valueGreaterThanQualifier = 0;
						for(x = 0; x < valueElement.length; x++){
							var valueQualifier = valueElement[x].value + "-" + qualifierElement[x].value;
							if(document.getElementById('type').value == "dollar" && (parseInt(valueElement[x].value) > parseInt(qualifierElement[x].value))){
								valueGreaterThanQualifier++;
								break;
							}
							if(valueQualifierElement.length > 0 && $.inArray(valueQualifier, valueQualifierElement)  >= 0){
								sameValueQualifierErrorCounter++;
								break;
							}
							valueQualifierElement.push(valueQualifier);
							
						}
						
						if(sameValueQualifierErrorCounter > 0){
							showError(discountVal,errorHandler.VALUE_QUALIFIER_NOT_SAME);
							countError++;
						}else if(valueGreaterThanQualifier > 0){
							showError(discountVal,errorHandler.VALUE_LESS_THAN_QUALIFIER);
							countError++;
						}else{
							removeError(discountVal); 
						}
					}
				}
		//end
	    
		
		
	    

		//ticket #342 - able to save same date 
		//gconstantino 11/13/2012
		//start
		//countError += checkIfEmpty(startDate);
	    //countError += checkIfEmpty(endDate);
		
		
		var dateError = 0;
		var startDateElement = document.getElementById(startDate.id);
		var endDateElement = document.getElementById(endDate.id);	
		if(startDateElement.value == ""){
			showError(startDateElement,errorHandler.NOT_EMPTY);
	        dateError++;
		}else{
			removeError(startDateElement);
		}
		
		if(endDateElement.value == ""){
			showError(endDateElement,errorHandler.NOT_EMPTY);
	        dateError++;
		}else{
			removeError(endDateElement);
		}
		countError += dateError;
		if(dateError == 0){
			if(startDateElement.value == endDateElement.value){
				showError(startDateElement,errorHandler.INVALID_DATE_NOT_EQUAL);
				countError++;
			}else{
				removeError(startDateElement);
			}
		}
		//end
		
	    countError += checkIfEmpty(siteId);
		
	    
		var initialQuantityCounter = 0;
		document.getElementById(initialQuantity.id).value = removeLeadingZero(document.getElementById(initialQuantity.id).value);
		var initialQuantityElement = document.getElementById(initialQuantity.id);
		var initialQuantityValue = initialQuantityElement.value.trim();
		
			if(initialQuantityValue == ""){
				showError(initialQuantityElement,errorHandler.NOT_EMPTY);
	            countError++;
	            initialQuantityCounter++;
			}else if(!isInt(initialQuantityValue)){
				showError(initialQuantityElement,errorHandler.IS_NUMERIC);
	            countError++;
				initialQuantityCounter++;
			}else if(parseInt(initialQuantityValue) == 0){
				showError(initialQuantityElement,errorHandler.NOT_ZERO);
				countError++;
				initialQuantityCounter++;
			}else{
				removeError(initialQuantityElement);
			}
		//countError += checkWorkerStatus(initialQuantityElement);	
		
		// # Name: Del # Date Modify: April 2016 #Start
		var lowerLimitCounter = 0;
		document.getElementById(lowerLimit.id).value = removeLeadingZero(document.getElementById(lowerLimit.id).value);
		var lowerLimitElement = document.getElementById(lowerLimit.id);
		var lowerLimitValue = lowerLimitElement.value.trim();
		
			if(lowerLimitValue == ""){
				showError(lowerLimitElement,errorHandler.NOT_EMPTY);
	            countError++;
	            lowerLimitCounter++;
			}else if(!isInt(lowerLimitValue)){
				showError(lowerLimitElement,errorHandler.IS_NUMERIC);
	            countError++;
				lowerLimitCounter++;
			}else if(parseInt(lowerLimitValue) == 0){
				showError(lowerLimitElement,errorHandler.NOT_ZERO);
				countError++;
				lowerLimitCounter++;
			}else{
				if(parseInt(lowerLimitValue) > parseInt(initialQuantityValue)){
					showError(lowerLimitElement,errorHandler.LOWER_LIMIT_GREATER_THAN_NUMBER_OF_COUPONS);
					countError++;
					lowerLimitCounter++;
				}else{
					removeError(lowerLimitElement);
				}
			}
		// # Name: Del # Date Modify: April 2016 #End

	    if($("#"+publish.id).is(":checked")){
	        if($("#"+generate.id).is(":checked")){
	            removeError(generate);
	        }else{
	            showError(generate,errorHandler.GENERATE_BEFORE_PUBLISH);
	            countError++;
	        }
	    }
	        
	    if(countError>0){
	        $('#couponErrorTable').show();
	        $('#couponErrorRow1').show();
	        $('#couponErrorRow2').show();
	        return false;
	    }else{
	        $('#couponErrorTable').hide();
	        $('#couponErrorRow1').hide();
	        $('#couponErrorRow2').hide();
	        return true;
	    }
	}
	catch(error){
		alert(error);
		return false;
	}
}
    
function showError(element, error){
    //$(element).addClass('errorFocus');
    $('.'+element.id).html(error);
}

function removeError(element){
    //$(element).removeClass('errorFocus');
    $('.'+element.id).html("");
}

function isInt(value){
	return (intRegex.test(value) || floatRegex.test(value));
}
//ticket #333 - Able to input numeric values which starts with zero in Number of coupons[One time use coupon] Add/Edit One time use coupon entry
//gconstantino 11/14/2012
//start
function removeLeadingZero(value){
	return value.replace(/\s/g,"");
}
//end

function checkIfEmpty(input, append){
    var append = (append == null) ? "" : append;
    var inputValue = $(append+'#'+input.id).val();
    if(inputValue == ""){
        $(append+'#'+input.id).addClass('errorFocus');
        $(append+'.'+input.id).html(input.label + " " + errorHandler.NOT_EMPTY);
        return 1;
    }else{
        $(append+'#'+input.id).removeClass('errorFocus');
        $(append+'.'+input.id).html("");
        return 0;
    }
}

function hasCoupon(){
    var inputData = $("#"+coupon_name.id).val();
    var errorCount = 0;
    jQuery.ajax({
        url: "ajax/?action=checkotucouponname",
        type: "GET",
        data: jQuery("#addcoupon_id").serialize(),
        async: false,

        success: function(data){
            if(data>0){
                $('#'+coupon_name.id).addClass('errorFocus');
                $('.'+coupon_name.id).html(errorHandler.COUPON_EXISTS + ": " + inputData);
                errorCount++;
            }else{
                $('#'+coupon_name.id).removeClass('errorFocus');
                $('.'+coupon_name.id).html("");
            }
        }
    });
    
    return errorCount;
}


function checkWorkerStatus(initialQuantityElement){
var quantity = parseInt(initialQuantityElement.value.trim());
var errorCounter = 0;
if(quantity > oneTimeUseLimit){
	$.ajax({
			url: "/dcms/otucoupon/checkstatus/format/json",
			type: "GET",
			datatype: "json",
			async: false,
			success: function(data){
					if(typeof data =='object'){
						if(data.status && data.status != "done"){
							errorCounter = 1;
							showError(initialQuantityElement,errorHandler.WORKER_UNAVAILABLE + data.batch_name);
						}else{
							errorCounter = 0;
							removeError(initialQuantityElement);
						}
					}else{
						errorCounter = 1;
						showError(initialQuantityElement,"Session expired.");

					}
				},
			error: function(err){
				errorCounter = 1;
			}

	});	
}else{
	errorCounter = 0;
}
	
	return errorCounter;
}

function getChannelCodes(){
    jQuery('#records_tab_wrapperonly').hide();
    jQuery('#results').hide();
    
    jQuery.ajax({
        url: "ajax/?action=getchannelcodestoadd",
        type: "GET",
        data: jQuery("#addcoupon_id").serialize(),
        async: false,

        success: function(data){
            jQuery('#records_tab_wrapperonly').show();
            jQuery('#results').show();
            jQuery("#records_tab_wrapperonly").html(data);
            jQuery('#results').fadeIn(200);
        }
    });
}

function bc_SplitTableRow(theLink) {
    var table = document.getElementById("couponTable");

    if(table.rows.length == 10){ 
        return false;
    }
    
	theRow   = theLink.parentNode.parentNode;
    theBod   = theRow.parentNode;
    theTable = theRow.parentNode;
    newRow   = theRow.cloneNode(true);
    
    try{
        new_id = Number(jQuery('#last_coupon_field_id').val())+1;
        $('#'+discountVal.id, newRow).val("");
        $('#'+amountQualifier.id, newRow).val("");
        $('#'+coupon_name.id, newRow).remove();
        $('#'+type.id, newRow).remove();
        $('#'+ceilingAmount.id, newRow).remove();
		newRow.cells[4].innerHTML = "";
        jQuery('#last_coupon_field_id').val(new_id);

        theBod.appendChild(newRow);
        jQuery("#minus").css("display", "block");
    }catch(error){
        alert(error);
    }

    return false;
}

function deleteRow(i){
    var table = document.getElementById("couponTable");
    if(table.rows.length == 2){
        alert('Cannot delete all discounts');
    } else if(i == 1){
        return false;
    }
    else{
        document.getElementById('couponTable').deleteRow(i);
    }
}

function checkNumber(val) {
    var strPass = val.value;
    var strLength = strPass.length;
    var lchar = val.value.charAt((strLength) - 1);
    var cCode = CalcKeyCode(lchar);
	//#321
	if(strPass.charAt(0) == 0 && val.id != amountQualifier.id){
		var myNumber = val.value.substring(0, (strLength) - 1);
        val.value = myNumber;
	}else if(val.id == amountQualifier.id && strLength > 1 && parseInt(strPass.charAt(0)) == 0){
		var myNumber = val.value * 1;
        val.value = myNumber;
	}
    /* Check if the keyed in character is a number
     do you want alphabetic UPPERCASE only ?
     or lower case only just check their respective
     codes and replace the 48 and 57 */
    if ((cCode < 48 || cCode > 57)) {
        var myNumber = val.value.substring(0, (strLength) - 1);
        val.value = myNumber;
    }
	
	if(!isInt(strPass)){
		var myNumber = val.value.substring(0, - parseInt(strLength));
        val.value = myNumber;
	}
	
	
    return false;
}

function CalcKeyCode(aChar) {
    var character = aChar.substring(0,1);
    var code = aChar.charCodeAt(0);
    return code;
}

function enableDisable(){
    if(document.getElementById('restrictions').disabled==true){
        $("#restrictions").attr("disabled", false);
            document.getElementById("viewTemplate").style.display = "block";
            
    }else{
        $("#restrictions").attr("disabled", true);
        document.getElementById("viewTemplate").style.display = "none";
    }
}

function activate_restriction_opts(chk, template) {
    if(!chk.checked){
        document.getElementById(template).setAttribute('disabled', true);
        document.getElementById("viewTemplate").style.display = "none";
    }else{
        if(document.getElementById(template).length > 0){
            document.getElementById(template).removeAttribute('disabled');
            document.getElementById("viewTemplate").style.display = "block";
        }else{
            $("#enabledisable_restrictions").attr('checked', false); 
        }
    }
        
}

function letternumber(e, checkNumber, allowSpace)
{
    var key;
    var keychar;

    if (window.event)
        key = window.event.keyCode;
    else if (e)
        key = e.which;
    else
        return true;
    keychar = String.fromCharCode(key);
    keychar = keychar.toLowerCase();

    // control keys
    if ((key==null) || (key==0) || (key==8) || 
        (key==9) || (key==13) || (key==27) )
        return true;

	var isNumber = (key >= 48 && key <= 57);
	var isLowerCaseLetter = (key >=97 && key <= 122);
	var isUCaseLetter = (key >= 65 && key <= 90);
        var isSpace = (key == 32)

	
    if (typeof(checkNumber) != 'undefined' && checkNumber !== null){
		if(isNumber){
			return true;
		}else{
			return false;
		}
    }else if(typeof(allowSpace) != 'undefined' && allowSpace !== null){
        if (isLowerCaseLetter ||
            isUCaseLetter ||
            isNumber ||
            isSpace
        ){
                return true;
        }else{
                return false;
        }
    }else{
		if (isLowerCaseLetter ||
			isUCaseLetter ||
			isNumber
		){
			return true;
		}else{
			return false;
		}
	}
        
}

var maxDateVar = '<?php echo date(strtotime("Y-m-d +10 year")); ?>';
    
$(document).ready(function() {
	var dates = $( "#startDate, #endDate" ).datepicker({
            defaultDate: "today",
            changeMonth: true,
            numberOfMonths: 1,
            dateFormat: 'mm/dd/yy',
            minDate: new Date(), 
            //            maxDate: new Date(2012,6, 27),
            onSelect: function( selectedDate ) {
                var option = this.id == "startDate" ? "minDate" : "maxDate",
                instance = $( this ).data( "datepicker" ),
                date = $.datepicker.parseDate(
                instance.settings.dateFormat ||
                    $.datepicker._defaults.dateFormat,
                selectedDate, instance.settings );
                dates.not( this ).datepicker( "option", option, date );
            }
        });
	getChannelCodes();
        
       $("#"+couponAppliesTo.id).change(function(){
                if(this.value == "ORDERTOTAL" || this.value == "SHIPPING"){
                    document.getElementById("viewTemplate").style.display = "none";
                    $("#enabledisable_restrictions").attr("disabled", true);
                    $("#"+restrictions.id).attr("disabled", true);
                }else{
                    activate_restriction_opts(document.getElementById('enabledisable_restrictions'), 'restrictions');
                    $("#enabledisable_restrictions").attr("disabled", false);
                }   
            
        });
});

function viewTemplate(link,windowName,id){
    var templateId = $("select#"+id+" option:selected").val();
    var params;
    params = 'width='+screen.width;
    params += ', height='+screen.height;
    params += ', top=0, left=0';
    params += ', fullscreen=yes, scrollbars=yes';
    
    window.open(link.href+""+templateId, windowName, params);
    //popView(link.href+""+templateId, windowName)
    return false;
}
</script>
<div class="container">
    <?php echo $this->partial('partials/tabs.phtml', $this); ?>
    <div class="tabbed-content content-tab">
        <form id="addcoupon_id" name="addcoupon" class="dataform" action="" method="post" enctype="application/x-www-form-urlencoded">
        <div id="main">
            Please be advised that the system converts the date you will set to <b><?php echo $this->timezone;  ?></b> timezone.
            <br />
            <br />
            <div class="messages"> 
            <?php echo $this->flashMessages(); ?> 
        	</div> 
            <div id="coupon-name">
                <table width="615" border="0" cellpadding="0" cellspacing="5" id="couponTable" style="table-layout:fixed;">
                    <tbody>
                        <tr>
                            <td width="150"><?php echo $name->getLabel(); ?></td>
                            <td width="85"><?php echo $type->getLabel(); ?></td>
                            <td width="85"><?php echo $discountVal->getLabel(); ?></td>
                            <td width="85"><?php echo $amountQualifier->getLabel(); ?></td>
                            <td width="85"><?php echo $ceilingAmount->getLabel(); ?></td>
                            <td width="15">&nbsp;</td>
                            <td width="15">&nbsp;</td>
                        </tr>
                        <tr>
                            <td valign="top"><?php echo $name; ?></td>
                            <td valign="top"><?php echo $type; ?></td>
                            <td valign="top"><?php echo $discountVal; ?></td>
                            <td valign="top">$<?php echo $amountQualifier; ?></td>
                            <td valign="top">$<?php echo $ceilingAmount; ?></td>
                            <td valign="top" align="center"><?php echo $plus; ?></td>
                            <td valign="top" align="center"><?php echo $minus; ?></td>
                        </tr>
                       
                    </tbody>
                </table>
                <table width="615" border="0" cellpadding="0" cellspacing="5" id="couponErrorTable" style="table-layout:fixed; display:none;">
                    <tbody>
                        <tr>
                            <td width="150" valign="top"><div class="error <?php echo $name->getId(); ?>"></div></td>
                            <td width="85">&nbsp;</td>
                            <td width="85" valign="top"><div class="error <?php echo $discountVal->getId(); ?>"></div></td>
                            <td width="85" valign="top"><div class="error <?php echo $amountQualifier->getId(); ?>"></div></td>
                            <td width="85" valign="top"><div class="error <?php echo $ceilingAmount->getId(); ?>"></div></td>
                            <td width="15">&nbsp;</td>
                            <td width="15">&nbsp;</td>
                        </tr>
                    </tbody>
                </table>
                <table width="615" border="0" cellpadding="0" cellspacing="5" id="couponTable" style="table-layout:fixed;">
                    <tbody>
                 <tr>
                            <td width="150" colspan="2"><?php echo $description->getLabel(); ?></td>
                            <td width="85">&nbsp;</td>
                            <td width="85">&nbsp;</td>
                            <td width="85">&nbsp;</td>
                            <td width="15">&nbsp;</td>
                            <td width="15">&nbsp;</td>
                        </tr>
                        <tr>
                            <td valign="top" colspan="2"><?php echo $description; ?><div class="error <?php echo $description->getId(); ?>"></div></td>
                            <td valign="top">&nbsp;</td>
                            <td valign="top">&nbsp;</td>
                            <td valign="top">&nbsp;</td>
                            <td valign="top">&nbsp;</td>
                            <td valign="top">&nbsp;</td>
                        </tr>
                  </tbody>
                </table>
                <?php echo $hidden; ?>
            </div>
            <div id="apply-coupon">
                <table width="100%" border="0" cellpadding="0" cellspacing="2">
                    <tr>
                        <td colspan="3"><b>Apply coupon to:</b></td>
                    </tr>
                    <tr>
                        <td><?php echo $class->getLabel()." ".$class; ?></td>
                        <td><?php echo $siteId->getLabel()." ".$siteId; ?></td>
                        <td>
                            <!--<div id="results">
                                <div id="records_tab_wrapperonly"></div>
                            </div>-->
                        </td>
                        <td><?php echo $couponAppliesTo->getLabel()." ".$couponAppliesTo; ?></td>
                    </tr>
                    <tr id="couponErrorRow1" style="display:none;">
                        <td>&nbsp;</td>
                        <td valign="top" align="left"><div class="error <?php echo $siteId->getId(); ?>"></div></td>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                    </tr>
                </table>
                <table width="100%" border="0" cellpadding="0" cellspacing="2">
                    <tr>
                        <td>&nbsp;</td>
                    </tr>
                    <tr>
                        <td><?php echo $owner->getLabel()." ".$owner; ?></td>
                    </tr>
                    <tr>
                        <td>&nbsp;</td>
                    </tr>
                    <tr>
                        <td><?php echo $appeasement->getLabel()." ".$appeasement; ?></td>
                    </tr>
                    <tr>
                        <td>&nbsp;</td>
                    </tr>
                </table>
                <table width="100%" border="0" cellpadding="0" cellspacing="2">
                    <tr>
                        <td colspan="4"><b>Expiration:</b></td>
                    </tr>
                    <tr>
                        <td width="70"><?php echo $startDate->getLabel(); ?></td>
                        <td width="200"><?php echo $startDate; ?></td>
                        <td width="70"><?php echo $endDate->getLabel(); ?></td>
                        <td><?php echo $endDate; ?></td>
                    </tr>
                    <tr id="couponErrorRow2" style="display:none;">
                        <td>&nbsp;</td>
                        <td valign="top"><div class="error <?php echo $startDate->getId(); ?>"></div></td>
                        <td>&nbsp;</td>
                        <td valign="top"><div class="error <?php echo $endDate->getId(); ?>"></div></td>
                    </tr>
                </table>
                <table width="100%" border="0" cellpadding="0" cellspacing="2">
                    <tr>
                        <td colspan="6">&nbsp;</td>
                    </tr>
                    <tr>
                        <td width="87"><?php echo $initialQuantity->getLabel(); ?></td>
                        <td width="100"><?php echo $initialQuantity; ?></td>
                        <td width="147"><?php echo $lowerLimit->getLabel(); ?></td>
                        <td width="100"><?php echo $lowerLimit; ?></td>
                    </tr>
                    <tr>
                        <td width="87"></td>
                        <td width="100">
	                        <div class="error <?php echo $initialQuantity->getId(); ?>"></div>
                        </td>
                        <td width="147"></td>
                        <td width="100">
                        	<div class="error <?php echo $lowerLimit->getId(); ?>"></div>
                        </td>
                    </tr>
                </table>
                <div>&nbsp;</div>
            </div>
            <div id="include-exclude">
                <div style="clear:both;"></div>
                <ul class="tab">
                    <li class="active" style=""><a href="#tab1"><b>Restrictions</b></a></li>
                </ul>
                <div class="lists">       
                    <div style="float: left; display: block; " id="tab1" class="tab_content">
                        <div id="left-variable">
                            <div style="width:600px;">
                                <table>
                                    <tbody>
                                        <tr>
                                            <td><?php echo $enabledisable_restrictions->getLabel()." ".$enabledisable_restrictions; ?> &nbsp; </td>
                                            <td><?php echo $restrictions; ?></td>
                                            <td>
                                                <div id="viewTemplate" style="display:none">
                                                    <a style='cursor:pointer' href="/dcms/template/view/tid/" 
                                                       onclick='return viewTemplate(this, "viewTemplate", "<?php echo $restrictions->getId(); ?>");'>
                                                        <u>view</u>
                                                    </a>
                                                </div>    
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div>&nbsp;</div>
            <div align="right">
                <?php echo $generate->getLabel()." ".$generate; ?>
                <br><br>
                <?php echo $publish->getLabel()." ".$publish; ?>
                <div class="error <?php echo $generate->getId(); ?>"></div>
                <br>
                <?php echo $dispense->getLabel()." ".$dispense; ?>
                <br>
                <?php echo $gated;?>
                <br><br><br><br>
                Dispense URI: [site]/redeem/[batchID]	
            </div>
            <div>&nbsp;</div>
            <div class="bg_btn"><?php echo $cancel.' '.$coupon_add; ?></div>
        </div>
        </form>
    </div>
</div>