<style>
#main .pagination {
    float: right;
    text-align: right;
    width: 620px;
}

.pagination a {
    color: #FFFFFF !important;
}

.pagination .disabled a {
    color: #737373 !important;
}
</style>
<script>  
$(function() {
    var dates = $( "#fromDate, #toDate" ).datepicker({
        defaultDate: "today",
        changeMonth: true,
        numberOfMonths: 1,
        dateFormat: 'M dd, yy',
        onSelect: function( selectedDate ) {
            var option = this.id == "fromDate" ? "minDate" : "maxDate",
            instance = $( this ).data( "datepicker" ),
            date = $.datepicker.parseDate(
            instance.settings.dateFormat ||
                $.datepicker._defaults.dateFormat,
            selectedDate, instance.settings );
            dates.not( this ).datepicker( "option", option, date );
        }
    });        
});

function filterRecords(){
    var type     = $("#type").val();
    var fromDate = $("#fromDate").val();
    var toDate   = $("#toDate").val();
    
    location.href = '/dcms/coupon/production/countperpage/<?php echo $this->request['countperpage']; ?>/page/<?php echo $this->request['page']; ?>/type/'+type+'/fromDate/'+fromDate+'/toDate/'+toDate;
}
</script>
<div class="container">
    <?php echo $this->partial('partials/tabs.phtml', $this); ?>
    <div class="tabbed-content content-tab">
        <form id="searchcoupon_id" name="searchcoupon" class="datasearchform" action="" method="post" enctype="application/x-www-form-urlencoded">
        <div id="main">
            <div id="coupon-name">
                <table width="100%" border="0" cellpadding="0" cellspacing="0" id="couponSearchTable">
                    <tr>
                        <td valign="top">
                            <b>Coupon Type:</b> 
                            <select id="type" name="type">

								<option value="" <?php echo  ($this->request['type'] == "") ? " selected='selected'" : ""; ?>>All</option>
                                <option value="expiring" <?php echo  ($this->request['type'] == "expiring") ? " selected='selected'" : ""; ?>>Expiring</option>
                                <option value="onetimeuse" <?php echo  ($this->request['type'] == "onetimeuse") ? " selected='selected'" : ""; ?>>One-Time Use</option>
                                <option value="firstxusers" <?php echo  ($this->request['type'] == "firstxusers") ? " selected='selected'" : ""; ?>>First X Users</option>
                                <option value="recurring" <?php echo  ($this->request['type'] == "recurring") ? " selected='selected'" : ""; ?>>Recurring</option>
                                <option value="nonexpiring" <?php echo  ($this->request['type'] == "nonexpiring") ? " selected='selected'" : ""; ?>>Non-Expiring</option>
                                <?php /* 
                                $rec = array(
                                        0=>array(0=>"expiring", 1=>"Expiring"), 
                                        1=>array(0=>"onetimeuse", 1=>"One-Time Use"), 
                                        2=>array(0=>"firstxusers", 1=>"First X Users"), 
                                        3=>array(0=>"recurring", 1=>"Recurring"),
                                        4=>array(0=>"nonexpiring",1=>"Non-Expiring")
                                    );
                              
                                $t = count($rec);

                                if(trim($t)){
                                    for($i=0; $i<$t; $i++){
                                        $optionpage1 = "<option value='{$rec[$i][0]}'";
                                        ($this->request['type'] == $rec[$i][0]) ? $optionpage1 .= " selected='selected'" : "";
                                        $optionpage1 .= ">{$rec[$i][1]}</option>";
                                        echo $optionpage1;
                                    }
                                }*/ 
                                ?>
                            </select>
                            &nbsp;&nbsp;&nbsp;&nbsp;
                            <b>Cut-off Date:</b> from <input type="text" id="fromDate" name="fromDate" class="uniform text" style="width:70px;" value="<?php if(isset($this->request['fromDate'])){echo $this->request['fromDate'];} ?>" /> &nbsp;&nbsp;&nbsp; to <input type="text" id="toDate" name="toDate"  class="uniform text" style="width:70px;" value="<?php if(isset($this->request['toDate'])){echo $this->request['toDate'];} ?>" />
                            &nbsp;&nbsp;
                            <input type="button" id="search_btn" name="search_btn" value="Filter" class="uniform" onclick="filterRecords();" />
                        </td>
                    </tr>
                </table>
            </div>
            <div id="apply-coupon" style="overflow:auto;">
                <div>&nbsp;</div>
                <div>
                    Coupon per page: 
                    <select name="countperpage" onchange="location.href='/dcms/coupon/production/countperpage/'+this.value+'/page/<?php echo $this->request['page']; ?>/type/<?php echo $this->request['type']; ?>/fromDate/<?php echo $this->request['fromDate']; ?>/toDate/<?php echo $this->request['toDate']; ?>';">
                        <?php
                        $pagecount = 10;
                        for ($counter = 1; $counter <= 10; $counter++, $pagecount += 10) {
                            $optionpage = "<option value='{$pagecount}'";
                            ($this->request['countperpage'] == $pagecount) ? $optionpage .= " selected='selected'" : "";
                            $optionpage .= ">{$pagecount}</option>";
                            echo $optionpage;
                        }
                        ?>
                    </select>
                </div>
                <div>&nbsp;</div>
                <!--<div><input type="submit" id="delete_id" name="delete" value="Delete" class="uniform" onClick="return confirm('Are you sure you want to DELETE all checked records?');" /></td></div>-->
                <?php $pagevars = $this->paginator->getPages(); ?>
                <table width="100%" border="0" cellpadding="0" cellspacing="2" id="couponTable">
                    <tr>
                        <td colspan="6">
                            <div class="pagination">
                                <div class="page-info"><?php echo $pagevars->totalItemCount; ?></div>
                                <?php echo $this->paginationControl($this->paginator, 'Sliding', '/partials/productionpaginationcontrols.phtml', array('request' => $this->request)); ?>
                            </div>
                        </td>
                    </tr>
                    <tr style="background-color:#FFEBCD;">
                        <!--<td width="5"><div style="padding:5px;"><input type="checkbox" id="checkAllAuto" name="checkAllAuto" /></div></td>-->
                        <td width="100" style="text-align:center;"><div style="padding:5px;"><b>Coupon</b></div></td>
                        <td width="100" style="text-align:center;"><div style="padding:5px;"><b>Username</b></div></td>
                        <td width="100" style="text-align:center;"><div style="padding:5px;"><b>Trans Type</b></div></td>
                        <td style="text-align:center;"><div style="padding:5px;"><b>Date & Time</b></div></td>
                        <td width="100" style="text-align:center;"><div style="padding:5px;"><b>Coupon Type</b></div></td>
                        <td width="80" style="text-align:center;"><div style="padding:5px;"><b>Status</b></div></td>
                    </tr>

                    <?php
                    if (count($this->paginator)) {
                        echo $this->partialLoop('partials/production.listing.phtml', $this->paginator);
                    }else{
                        echo '<tr>
                            <td colspan="6"><center>No coupon available</center></td>
                        </tr>
                        <tr>
                            <td colspan="6">&nbsp;</td>
                        </tr>';
                    }
                    ?>

                    <tr>
                        <td colspan="6">
                            <div class="pagination">
                                <div class="page-info"><?php echo $pagevars->totalItemCount; ?></div>
                                <?php echo $this->paginationControl($this->paginator, 'Sliding', '/partials/productionpaginationcontrols.phtml', array('request' => $this->request)); ?>
                            </div>
                        </td>
                    </tr>
                </table>
            </div>
        </div>
        </form>
    </div>
</div>
