<?php
echo $this->headLink()->prependStylesheet('/assets/css/coupon.css');
echo $this->headLink()->prependStylesheet('/assets/css/jquery/jcarousel-skin-tango.css');
$key = rand(0, 9999);
$this->headScript()->appendFile("/assets/js/function.js?q=" . $key);
$this->headScript()->appendFile("/assets/js/jquery/jquery.jcarousel.min.js?q=" . $key);
?>
<style>
    .bg_btn {
        background-color: #F6F6F6;
        border-bottom: 5px solid #555555;
        border-top: 5px solid #555555;
        margin-top: 20px;
        padding: 8px 10px;
        text-align: right;
    }
</style>
<div class="container">
    <?php echo $this->partial('partials/tabs.phtml', $this); ?>
    <div class="tabbed-content content-tab">
        <div id="main">
            <div class="messages">
                <?php echo $this->flashMessages(); ?>
            </div>
            <?php if(isset($this->form)) : 
                ?>
            <form action="<?php echo $this->form->getAction(); ?>"
                  enctype="<?php echo $this->form->getEnctype(); ?>"
                  method="<?php echo $this->form->getMethod(); ?>"
                  id="<?php echo $this->form->getId(); ?>"
                  name="<?php echo $this->form->getName(); ?>"
                  class="<?php echo $this->form->getAttrib('class'); ?>"
            >
                
                <div id="include-exclude">
                    <div style="padding-bottom: 20px;" class="contollermessage">Template Name: <?php echo $this->form->getElement('template_name'); ?>&nbsp;<?php echo $this->form->getElement('exinradio');?>
                        <br>
                        <br>
                        <?php echo $this->form->getElement('restriction_selector_select'); ?>
                    </div>

                    <div class="lists" style="width: 100%">
                        
                        <!-- PART TEMPLATE -->
                        <div style="float: left; display: none;" id="parttemplate" class="tab_contents">
                            <div style="width:100%">
                                <div style="width: 100%">
                                    <div style="float: left; width: 297px; margin-right: 6px; border: 1px solid #D5D5D5; ">
                                        <div style="height: 30px; background-color: #25609D;">
                                            <div style="float:left; font-weight: bold; color: #FFF; margin-top:5px; padding-left: 2px; width: 130px; margin-left:2px;">Parts</div>
                                            <div style="float:left; margin-top: 5px; width: 120px;"><?php echo $this->form->getElement('restriction_part_selector_search');?></div>
                                            <div style="clear:both;"></div>
                                        </div>
                                        <div>
                                            <?php echo $this->form->getElement('restriction_part_list'); ?>
                                            
                                        </div>
                                    </div>
                                    <div style="float: left; width: 297px; border: 1px solid #D5D5D5;">
                                        <div style="height: 30px; background-color: #25609D;">
                                            <div style="float:left; font-weight: bold; color: #FFF; margin-top:5px; padding-left: 2px; width: 130px; margin-left:2px;">Selected Parts</div>
                                            <div style="clear:both;"></div>
                                        </div>
                                        <div>
                                            <?php echo $this->form->getElement('restriction_part_selected'); ?>
                                        </div>
                                    </div>
                                    <div style="clear:both;"></div>
                                </div>
                            </div>
                        </div>
                        <!-- END OF PART TEMPLATE -->

                        <!-- BRAND TEMPLATE -->
                        <div style="float: left; display: none;" id="brandtemplate" class="tab_contents">
                            <div style="width: 100%">
                                <div style="width: 100%">
                                    <div style="float: left; width: 297px; margin-right: 6px; border: 1px solid #D5D5D5; ">
                                        <div style="height: 30px; background-color: #25609D;">
                                            <div style="float:left; font-weight: bold; color: #FFF; margin-top:5px; padding-left: 2px; width: 130px; margin-left:2px;">Brands</div>
                                            <div style="float:left; margin-top: 5px; width: 120px;"><?php echo $this->form->getElement('restriction_brand_selector_search'); ?></div>
                                            <div style="clear:both;"></div>
                                        </div>
                                        <div>
                                            <?php echo $this->form->getElement('restriction_brand_list');?>
                                        </div>
                                    </div>
                                    <div style="float: left; width: 297px; border: 1px solid #D5D5D5;">
                                        <div style="height: 30px; background-color: #25609D;">
                                            <div style="float:left; font-weight: bold; color: #FFF; margin-top:5px; padding-left: 2px; width: 130px; margin-left:2px;">Selected Brands</div>
                                            <div style="clear:both;"></div>
                                        </div>
                                        <div>
                                            <?php echo $this->form->getElement('restriction_brand_selected'); ?>
                                        </div>
                                    </div>
                                    <div style="clear:both;"></div>
                                </div>
                            </div>
                        </div>                        
                        <!-- END OF BRAND TEMPLATE -->
                        
                        <!-- END OF BRAND-PART TEMPLATE -->
                        <div style="float: left; display: none;" id="brandparttemplate" class="tab_contents">
                            <div style="100%">
                                <div style="width: 100%">
                                    <div style="float: left; width: 197px; margin-right: 3px; border: 1px solid #D5D5D5;">
                                        <div style="height: 30px; background-color: #25609D;">
                                            <div style="float:left; font-weight: bold; color: #FFF; margin-top:5px; padding-left: 3px; width: 65px">Brands</div>
                                            <div style="float:left; margin-top: 6px; width: 120px;"><?php echo $this->form->getElement('restriction_brand_part_selector_brand_search'); ?></div>
                                            <div style="clear:both;"></div>
                                        </div>
                                        <div>
                                            <?php echo $this->form->getElement('restriction_brand_part_brand_list');?>
                                        </div>
                                    </div>
                                    <div style="float: left; width: 197px; margin-right: 3px; border: 1px solid #D5D5D5;">
                                        <div style="height: 30px; background-color: #25609D;">
                                            <div style="float:left; font-weight: bold; color: #FFF; margin-top:5px; padding-left: 3px; width: 65px">Parts</div>
                                            <div style="float:left; margin-top: 6px; width: 120px;"><?php echo $this->form->getElement('restriction_brand_part_selector_part_search');?></div>
                                            <div style="clear:both;"></div>
                                        </div>
                                        <div>
                                            <?php echo $this->form->getElement('restriction_brand_part_part_list');?>
                                        </div>
                                    </div>
                                    <div style="float: left; width: 197px; border: 1px solid #D5D5D5;">
                                        <div style="height: 30px; background-color: #25609D;">
                                            <div style="float:left; font-weight: bold; color: #FFF; margin-top:5px; padding-left: 3px; width: 120px">Selected Parts</div>
                                            <div style="clear:both;"></div>
                                        </div>
                                        <div>
                                            <?php echo $this->form->getElement('restriction_brand_part_selected');?>
                                        </div>
                                    </div>
                                    <div style="clear:both;"></div>
                                </div>
                            </div>
                        </div>
                        <!-- END OF BRAND-PART TEMPLATE -->
                        
                        <!-- PART-BRAND TEMPLATE -->
                        <div style="float: left; display: none;" id="partbrandtemplate" class="tab_contents">
                            <div style="100%">
                                <div style="width: 100%">
                                    <div style="float: left; width: 197px; margin-right: 3px; border: 1px solid #D5D5D5;">
                                        <div style="height: 30px; background-color: #25609D;">
                                            <div style="float:left; font-weight: bold; color: #FFF; margin-top:5px; padding-left: 3px; width: 65px">Parts</div>
                                            <div style="float:left; margin-top: 6px; width: 120px;"><?php echo $this->form->getElement('restriction_part_brand_selector_part_search');?></div>
                                            <div style="clear:both;"></div>
                                        </div>
                                        <div>
                                            <?php echo $this->form->getElement('restriction_part_brand_part_list');?>
                                        </div>
                                    </div>
                                    <div style="float: left; width: 197px; margin-right: 3px; border: 1px solid #D5D5D5;">
                                        <div style="height: 30px; background-color: #25609D;">
                                            <div style="float:left; font-weight: bold; color: #FFF; margin-top:5px; padding-left: 3px; width: 65px">Brands</div>
                                            <div style="float:left; margin-top: 6px; width: 120px;"><?php echo $this->form->getElement('restriction_part_brand_selector_brand_search');?></div>
                                            <div style="clear:both;"></div>
                                        </div>
                                        <div>
                                            <?php echo $this->form->getElement('restriction_part_brand_brand_list');?>
                                        </div>
                                    </div>
                                    <div style="float: left; width: 197px; border: 1px solid #D5D5D5;">
                                        <div style="height: 30px; background-color: #25609D;">
                                            <div style="float:left; font-weight: bold; color: #FFF; margin-top:5px; padding-left: 3px; width: 120px">Selected Brands</div>
                                            <div style="clear:both;"></div>
                                        </div>
                                        <div/>
                                            <?php echo $this->form->getElement('restriction_part_brand_selected');?>
                                        </div>
                                    </div>
                                    <div style="clear:both;"></div>
                                </div>
                            </div>
                        </div>                         
                        <!-- END OF PART-BRAND TEMPLATE -->
                        
                        <!-- SKU TEMPLATE -->
                        <div style="float: left; display: none;" id="skutemplate" class="tab_contents">
                            <div style="100%">
                                <div style="width: 100%">
                                    <div style="float: left; width: 197px; margin-right: 3px; border: 1px solid #D5D5D5;">
                                        <div style="height: 30px; background-color: #25609D;">
                                            <div style="float:left; font-weight: bold; color: #FFF; margin-top:5px; padding-left: 3px; width: 65px">Brands</div>
                                            <div style="float:left; margin-top: 6px; width: 120px;"><?php echo $this->form->getElement('restriction_sku_selector_brand_search');?></div>
                                            <div style="clear:both;"></div>
                                        </div>
                                        <div>
                                            <?php echo $this->form->getElement('restriction_sku_brand_list');?>
                                        </div>
                                    </div>
                                    <div style="float: left; width: 197px; margin-right: 3px; border: 1px solid #D5D5D5;">
                                        
                                        <div style="height: 30px; background-color: #25609D;">
                                            <div style="float:left; font-weight: bold; color: #FFF; margin-top:5px; margin-right: 5px; padding-left: 3px; width: 70px">USAP Skus</div>
                                            <div style="float:left; margin-top: 6px; width: 112px;"><?php echo $this->form->getElement('restriction_sku_selector_sku_usap_search');?></div>
                                            <div style="clear:both;"></div>
                                        </div>
                                        <div>
                                            <?php echo $this->form->getElement('restriction_sku_sku_usap_list');?>
                                        </div>
                                        <br />
                                        <div style="height: 30px; background-color: #25609D;">
                                            <div style="float:left; font-weight: bold; color: #FFF; margin-top:5px; padding-left: 3px; width: 65px">JCW Skus</div>
                                            <div style="float:left; margin-top: 6px; width: 120px;"><?php echo $this->form->getElement('restriction_sku_selector_sku_jcw_search');?></div>
                                            <div style="clear:both;"></div>
                                        </div>
                                        <div>
                                            <?php echo $this->form->getElement('restriction_sku_sku_jcw_list');?>
                                        </div>
                                        <br />
                                        <div style="height: 30px; background-color: #25609D;">
                                            <div style="float:left; font-weight: bold; color: #FFF; margin-top:5px; padding-left: 3px; width: 65px">STT Skus</div>
                                            <div style="float:left; margin-top: 6px; width: 120px;"><?php echo $this->form->getElement('restriction_sku_selector_sku_stt_search');?></div>
                                            <div style="clear:both;"></div>
                                        </div>
                                        <div>
                                            <?php echo $this->form->getElement('restriction_sku_sku_stt_list');?>
                                        </div>
                                        
                                    </div>
                                    <div style="float: left; width: 197px; border: 1px solid #D5D5D5;">
                                        <div style="height: 30px; background-color: #25609D;">
                                            <div style="float:left; font-weight: bold; color: #FFF; margin-top:5px; padding-left: 3px; width: 120px">Selected Skus</div>
                                            <div style="clear:both;"></div>
                                        </div>
                                        <div>
                                            <?php echo $this->form->getElement('restriction_sku_selected');?>
                                        </div>
                                    </div>
                                    <div style="clear:both;"></div>
                                </div>
                            </div>
                        </div>                        
                        <!-- END OF SKU TEMPLATE -->
                    </div>
                    <?php //echo $this->form->getElement('Save'); ?><br /><br /><br />
                    
                </div>
                
                
                
                
                
                <!--<div id="dummy-loader"></div>-->
<script type="text/javascript" src="/assets/js/jquery/functions.js"></script>
<script type="text/javascript">
    
    var searchKeyword = "search";
    var beforeSearch = "";
    var pagesize = 30;
    var offsetPage = 0;
    
    var offsetHash = {};
    offsetHash.RESTRICTION_PART_LIST_OFFSET_SIZE = 0;
    offsetHash.RESTRICTION_PART_LIST_SEARCH_OFFSET_SIZE = 0;
    offsetHash.RESTRICTION_BRAND_LIST_OFFSET_SIZE = 0;
    offsetHash.RESTRICTION_BRAND_LIST_SEARCH_OFFSET_SIZE = 0;
    offsetHash.RESTRICTION_BRAND_PART_BRAND_LIST_OFFSET_SIZE = 0;
    offsetHash.RESTRICTION_BRAND_PART_BRAND_LIST_SEARCH_OFFSET_SIZE = 0;
    offsetHash.RESTRICTION_BRAND_PART_PART_LIST_OFFSET_SIZE = 0;
    offsetHash.RESTRICTION_BRAND_PART_PART_LIST_SEARCH_OFFSET_SIZE = 0;
    offsetHash.RESTRICTION_PART_BRAND_PART_LIST_OFFSET_SIZE = 0;
    offsetHash.RESTRICTION_PART_BRAND_PART_LIST_SEARCH_OFFSET_SIZE = 0;
    offsetHash.RESTRICTION_PART_BRAND_BRAND_LIST_OFFSET_SIZE = 0;
    offsetHash.RESTRICTION_PART_BRAND_BRAND_LIST_SEARCH_OFFSET_SIZE = 0;
    offsetHash.RESTRICTION_SKU_BRAND_LIST_OFFSET_SIZE = 0;
    offsetHash.RESTRICTION_SKU_BRAND_LIST_SEARCH_OFFSET_SIZE = 0;
    offsetHash.RESTRICTION_SKU_SKU_JCW_LIST_OFFSET_SIZE = 0;
    offsetHash.RESTRICTION_SKU_SKU_JCW_LIST_SEARCH_OFFSET_SIZE = 0;
    offsetHash.RESTRICTION_SKU_SKU_STT_LIST_OFFSET_SIZE = 0;
    offsetHash.RESTRICTION_SKU_SKU_STT_LIST_SEARCH_OFFSET_SIZE = 0;    
    offsetHash.RESTRICTION_SKU_SKU_USAP_LIST_OFFSET_SIZE = 0;
    offsetHash.RESTRICTION_SKU_SKU_USAP_LIST_SEARCH_OFFSET_SIZE = 0;      
    
    var searchHash = {};
    searchHash.RESTRICTION_PART_LIST_SEARCH = "search";
    searchHash.RESTRICTION_BRAND_LIST_SEARCH = "search";
    searchHash.RESTRICTION_BRAND_PART_BRAND_LIST_SEARCH = "search";
    searchHash.RESTRICTION_BRAND_PART_PART_LIST_SEARCH = "search";
    searchHash.RESTRICTION_PART_BRAND_PART_LIST_SEARCH = "search";
    searchHash.RESTRICTION_PART_BRAND_BRAND_LIST_SEARCH = "search";
    searchHash.RESTRICTION_SKU_BRAND_LIST_SEARCH = "search";
    searchHash.RESTRICTION_SKU_SKU_JCW_LIST_SEARCH = "search";
    searchHash.RESTRICTION_SKU_SKU_STT_LIST_SEARCH = "search";
    searchHash.RESTRICTION_SKU_SKU_USAP_LIST_SEARCH = "search";

    $(document).ready(function() {
        selectorDisplayType($("#restriction_selector_select").val(),"#restriction_selector_select");
    });
    
    function getObjectElementValue(object, objElement) {

        if(object.hasOwnProperty(objElement)) {
            return {elm:objElement, elvalue:object[objElement]};
        } else {
            return false;
        }
    }
    
    function selectorDisplayType(value, element) {
        
        var selectedValue = trimValue(value);
        $(element + ' option').each(function(index) {
           if($(this).val() == selectedValue) {
               $("#"+$(this).val()).show();
           } else {
               $("#"+$(this).val()).hide();
           }
        });
        
        var elementToPopulate = getSelectorValue(selectedValue);
        populateList(elementToPopulate);
    }
    
    function getSelectorValue(value) {

        switch (value) {
            case "parttemplate" :
                return {
                    elementId:"#restriction_part_list", 
                    elementOffsetSize:"RESTRICTION_PART_LIST_OFFSET_SIZE", 
                    method:"partlist",
                    selectedData: getAllSelectedValues("#restriction_part_selected")
                };
                break;
            case "brandtemplate" :
                return {
                    elementId:"#restriction_brand_list", 
                    elementOffsetSize:"RESTRICTION_BRAND_LIST_OFFSET_SIZE", 
                    method:"brandlist",
                    selectedData: getAllSelectedValues("#restriction_brand_selected")
                };
                break;
            case "brandparttemplate" :
                return {
                    elementId:"#restriction_brand_part_brand_list", 
                    elementOffsetSize:"RESTRICTION_BRAND_PART_BRAND_LIST_OFFSET_SIZE",
                    method:"brandlist"
                };
                break;
            case "partbrandtemplate" :
                return {
                    elementId:"#restriction_part_brand_part_list", 
                    elementOffsetSize:"RESTRICTION_PART_BRAND_PART_LIST_OFFSET_SIZE",
                    method:"partlist"
                };
                break;
            case "skutemplate" :
                return {
                    elementId:"#restriction_sku_brand_list", 
                    elementOffsetSize:"RESTRICTION_SKU_BRAND_LIST_OFFSET_SIZE",
                    method:"brandlist"
                };
                break;
            default :
                return {
                    elementId:"#restriction_part_list", 
                    elementOffsetSize:"RESTRICTION_PART_LIST_OFFSET_SIZE",
                    method:"partlist"
                };
                break;
        }
    }
    
    function populateList(elementToPopulate) {
        
        var size = getSelectOptionSize(elementToPopulate.elementId);
        
        if(size <= 0) {    
            var objElement = getObjectElementValue(offsetHash, elementToPopulate.elementOffsetSize);

            offsetHash[objElement.elm] = 0;
            offsetPage = offsetHash[objElement.elm];
            if(objElement != false) {
                loadElement("#dummy-loader", 
                    "/dcms/template/" + elementToPopulate.method, 
                    "post", 
                    (elementToPopulate.hasOwnProperty('selectedData')) ?
                        {offset:offsetPage,pagesize:pagesize, element:elementToPopulate.elementId, selected:elementToPopulate.selectedData} :
                        {offset:offsetPage,pagesize:pagesize, element:elementToPopulate.elementId} ,
                    null, 
                    MESSAGE_LOADING, 
                    'html',
                    elementToPopulate.elementId
                );
                offsetHash[objElement.elm] = objElement.elvalue + pagesize;
            }
        }
    }

    function searchBox(searchType, value, element, method, offsetSearchType, searchKeywordList, offsetList, dynamicElement, selectedDataElement, evt, parentSecondDegLvl, secondLvlOffsetKey) {
    
        if(typeof(evt) != 'undefined' && evt !== null){
            var charCode;
            
            if(evt == 13 || evt == "13") {
                charCode = 13;
            } else {
                evt = (evt) ? evt : event;
                charCode = (evt.charCode) ? evt.charCode : ((evt.keyCode) ? evt.keyCode : ((evt.which) ? evt.which : 0));
//                if(charCode != 32 && charCode != 8 && charCode != 46 && (charCode < 48 || charCode > 90) && (charCode < 96 || charCode > 105)) {
//                    return false;
//                }
            }
            if(charCode != 13) {
                return false;
            }
        }      
        
        if(typeof(parentSecondDegLvl) != 'undefined' && parentSecondDegLvl !== null){
            try {
                var parent = document.getElementById(parentSecondDegLvl);
                var parentpost = parent.options[parent.selectedIndex].value;
            } catch (error) {
                alert("Second degree level of searching. Please select on the first list.");
                return false;
            }
        }
        
        var objElementSearchHash = getObjectElementValue(searchHash, searchKeywordList);
        searchHash[objElementSearchHash.elm] = searchKeyword;//beforeSearch
        
        var objElementOffsetHash = getObjectElementValue(offsetHash, offsetSearchType);
        var objElementListOffsetHash = getObjectElementValue(offsetHash, offsetList)
       
        if(searchHash[objElementSearchHash.elm] != value) {//beforeSearch
            offsetHash[objElementOffsetHash.elm] = 0;
            offsetPage = 0;
            offsetHash[objElementListOffsetHash.elm] = 0;
            searchKeyword = value;
        } else {
            if(searchType == 'direct') {
                
                offsetHash[objElementOffsetHash.elm] = 0;
                offsetPage = offsetHash[objElementOffsetHash.elm];
            } else {
                offsetHash[objElementOffsetHash.elm] = objElementOffsetHash.elvalue + pagesize;
                offsetPage = offsetHash[objElementOffsetHash.elm];                                                
            }
        }
        /////FIXED ARRAY PUSH ////////
        var loadParam = [];
        if(typeof(parentSecondDegLvl) != 'undefined' && parentSecondDegLvl !== null){ 
            if(secondLvlOffsetKey == 'usap') {
                loadParam = {post:searchKeyword, offset:{usap:offsetPage}, pagesize:pagesize, search:true, element:{usap:dynamicElement}, selected:getAllSelectedValues(selectedDataElement), parentpost:parentpost};
            } else if(secondLvlOffsetKey == 'jcw') {
                loadParam = {post:searchKeyword, offset:{jcw:offsetPage}, pagesize:pagesize, search:true, element:{jcw:dynamicElement}, selected:getAllSelectedValues(selectedDataElement), parentpost:parentpost};
            } else if(secondLvlOffsetKey == 'stt') {
                loadParam = {post:searchKeyword, offset:{stt:offsetPage}, pagesize:pagesize, search:true, element:{stt:dynamicElement}, selected:getAllSelectedValues(selectedDataElement), parentpost:parentpost};
            } else {
                loadParam = {post:searchKeyword, offset:offsetPage, pagesize:pagesize, search:true, element:dynamicElement, selected:getAllSelectedValues(selectedDataElement), parentpost:parentpost};
            }
        } else {
            loadParam = {post:searchKeyword, offset:offsetPage, pagesize:pagesize, search:true, element:dynamicElement, selected:getAllSelectedValues(selectedDataElement)};
        }
        loadElement(
            element,
            "/dcms/template/" + method, 
            "post", 
            loadParam, 
            null, 
            MESSAGE_LOADING, 
            'html',
            dynamicElement
        );
    }
    
    /**
     * @param string    value
     * @param string    elementId
     * @param string    method
     * @param string    offsetType
     * @param boolean   loadNewList
     * @param string    newListElementId
     */
    function callList(value, element, method, offsetType, selectedDataElement, loadNewList, newListElementId, newListElementIdOffsetType, newListElementIdMethod, newElementSearchText, newElementSearchOffset, newElementSearchId) {

        if(value == 'append') {
            var objElement = getObjectElementValue(offsetHash, offsetType);
            if(objElement != false) {
                 $("#" + element +' option:selected').remove();
                 loadElement("#dummy-loader", 
                    "/dcms/template/" + method, 
                    "post", 
                    {offset:objElement.elvalue,pagesize:pagesize, element:"#" + element, selected:getAllSelectedValues(selectedDataElement)}, 
                    null, 
                    MESSAGE_LOADING, 
                    'html',
                    "#" + element
                );
                offsetHash[objElement.elm] = objElement.elvalue + pagesize;
            }
        } else if(value == 'append-search-part-list'){
            $("#" + element +' option:selected').remove();
            searchBox(
                'indirect',
                $('#restriction_part_selector_search').val(), 
                "#dummy-loader", 
                method, 
                'RESTRICTION_PART_LIST_SEARCH_OFFSET_SIZE', 
                'RESTRICTION_PART_LIST_SEARCH', 
                'RESTRICTION_PART_LIST_OFFSET_SIZE',
                "#" + element,
                '#restriction_part_selected'
            );
        } else if(value == 'append-search-brand-list'){
            $("#" + element +' option:selected').remove();
            searchBox(
                'indirect',
                $('#restriction_brand_selector_search').val(), 
                "#dummy-loader", 
                method, 
                'RESTRICTION_BRAND_LIST_SEARCH_OFFSET_SIZE', 
                'RESTRICTION_BRAND_LIST_SEARCH', 
                'RESTRICTION_BRAND_LIST_OFFSET_SIZE',
                "#" + element
            ); 
        } else if(value == 'append-search-brand-brand-list'){
            $("#" + element +' option:selected').remove();
            searchBox(
                'indirect',
                $('#restriction_brand_part_selector_brand_search').val(), 
                "#dummy-loader", 
                method, 
                'RESTRICTION_BRAND_PART_BRAND_LIST_SEARCH_OFFSET_SIZE', 
                'RESTRICTION_BRAND_PART_BRAND_LIST_SEARCH', 
                'RESTRICTION_BRAND_PART_BRAND_LIST_OFFSET_SIZE',
                "#" + element,
                '#restriction_brand_part_selected'
            ); 
        } else if(value == 'append-search-part-part-list'){
            $("#" + element +' option:selected').remove();
            searchBox(
                'indirect',
                $('#restriction_part_brand_selector_part_search').val(), 
                "#dummy-loader", 
                method, 
                'RESTRICTION_PART_BRAND_PART_LIST_SEARCH_OFFSET_SIZE', 
                'RESTRICTION_PART_BRAND_PART_LIST_SEARCH', 
                'RESTRICTION_PART_BRAND_PART_LIST_OFFSET_SIZE',
                "#" + element,
                '#restriction_part_brand_selected'
            ); 
        } else {            
            if(loadNewList) {
                var objElementSearchOffset = getObjectElementValue(offsetHash, newElementSearchOffset);
                offsetHash[objElementSearchOffset.elm] = 0;
                var objElementSearchHash = getObjectElementValue(searchHash, newElementSearchText);
                searchHash[objElementSearchHash.elm] = "search";
                var objElement = getObjectElementValue(offsetHash, newListElementIdOffsetType);
                offsetHash[objElement.elm] = 0;
                if(objElement != false) {
                    $(newListElementId).empty();
                    loadElement("#dummy-loader", 
                        "/dcms/template/" + newListElementIdMethod, 
                        "post", 
                        {offset:offsetHash[objElement.elm],pagesize:pagesize, element:newListElementId, post:value, selected:getAllSelectedValues(selectedDataElement)}, 
                        null, 
                        MESSAGE_LOADING, 
                        'html',
                        "#" + element
                    );
                    offsetHash[objElement.elm] = pagesize;
                }
                $(newElementSearchId).val('');
            }else {
                return false;
            }
        }
    }
    
    function secondLevelCheck(listType, value) {
        
        var trimListType = trimValue(listType);
        var trimValueSelected = trimValue(value);
        if(trimValueSelected == 'append' || trimValueSelected == 'zero-result') {
            return false;
        } else {
            if(trimListType == 'partlist') {
                
                listbox_moveacross(
                    'restriction_brand_part_part_list', 
                    'restriction_brand_part_selected', 
                    'restriction_brand_part_brand_list', 
                    'add'
                );
                
            } else if(trimListType == 'brandlist') {
              
                listbox_moveacross(
                    'restriction_part_brand_brand_list', 
                    'restriction_part_brand_selected', 
                    'restriction_part_brand_part_list', 
                    'add'
                );
            } else if(trimListType == 'usap' || trimListType == 'jcw' || trimListType == 'stt') {
                
                sku_listbox_moveacross(
                    'restriction_sku_sku_' + trimListType +'_list', 
                    'restriction_sku_selected', 
                    'restriction_sku_brand_list', 
                    'add',
                    trimListType
                );
            }
        }
    }   
    
    function getAllSelection() {
        
        var selectedPartValues = getAllSelectedValues("#restriction_part_selected");
        var selectedBrandValues = getAllSelectedValues("#restriction_brand_selected");
        var selectedBrandPartValues = getAllSelectedValues("#restriction_brand_part_selected");
        var selectedPartBrandValues = getAllSelectedValues("#restriction_part_brand_selected");
        var selectedSkuValues = getAllSelectedValues("#restriction_sku_selected");
        
        return {
            selectedPartValues:selectedPartValues, 
            selectedBrandValues:selectedBrandValues, 
            selectedBrandPartValues:selectedBrandPartValues, 
            selectedPartBrandValues:selectedPartBrandValues, 
            selectedSkuValues:selectedSkuValues
        }
    }
    
    function brandPartCallList(value, element, method, offsetType, firstListElement, selectedListElement) {
        
        try {
            var parent = document.getElementById(firstListElement);
            var post = parent.options[parent.selectedIndex].value;
        } catch (error) {
            alert("No selected option in the first select list.");
            return false;
        }
        
        if(value == 'append') {          
            var objElement = getObjectElementValue(offsetHash, offsetType);
            
            if(objElement != false) {
                $("#" + element +' option:selected').remove();

                var loadParam = {post:post, offset:objElement.elvalue,pagesize:pagesize, element:"#" + element, selected:getAllSelectedValues(selectedListElement)};
                             
                loadElement("#dummy-loader", 
                    "/dcms/template/" + method, 
                    "post", 
                    loadParam, 
                    null, 
                    MESSAGE_LOADING, 
                    'html',
                    "#"+element
                );
                offsetHash[objElement.elm] = objElement.elvalue + pagesize;
            }
        } else if(value == 'append-search-brandpart-list') {
            $("#" + element +' option:selected').remove();
            searchBox(
                'indirect',
                $('#restriction_brand_part_selector_part_search').val(), 
                "#dummy-loader", 
                method, 
                'RESTRICTION_BRAND_PART_PART_LIST_SEARCH_OFFSET_SIZE', 
                'RESTRICTION_BRAND_PART_PART_LIST_SEARCH', 
                'RESTRICTION_BRAND_PART_PART_LIST_OFFSET_SIZE',
                "#" + element,
                '#restriction_brand_part_selected',
                13,
                'restriction_brand_part_brand_list'
            );    
        }  else if(value == 'append-search-partbrand-list'){
            $("#" + element +' option:selected').remove();
            searchBox(
                'indirect',
                $('#restriction_part_brand_selector_brand_search').val(), 
                "#dummy-loader", 
                method, 
                'RESTRICTION_PART_BRAND_BRAND_LIST_SEARCH_OFFSET_SIZE', 
                'RESTRICTION_PART_BRAND_BRAND_LIST_SEARCH', 
                'RESTRICTION_PART_BRAND_BRAND_LIST_OFFSET_SIZE',
                "#" + element,
                '#restriction_part_brand_selected',
                13,
                'restriction_part_brand_part_list'
            ); 
        } else {
            return false;
        }
        
    }
    
    function skuCallList(value, element, method, offsetType, offsetSiteType) {
        
        try {
            var parent = document.getElementById('restriction_sku_brand_list');
            var post = parent.options[parent.selectedIndex].value;
        } catch (error) {
            alert("No brand is selected.");
            return false;
        }

        if(value == 'append') {          
            var objElement = getObjectElementValue(offsetHash, offsetType);
            
            if(objElement != false) {
                $("#" + element +' option:selected').remove();
                
                if(offsetSiteType == 'usap') {
                    var loadParam = {post:post, offset:{usap: objElement.elvalue},pagesize:pagesize, element:{usap: "#" + element}, selected:getAllSelectedValues('#restriction_sku_selected')};
                }
                if(offsetSiteType == 'jcw') {
                    var loadParam = {post:post, offset:{jcw: objElement.elvalue},pagesize:pagesize, element:{jcw: "#" + element}, selected:getAllSelectedValues('#restriction_sku_selected')};
                }
                if(offsetSiteType == 'stt') {
                    var loadParam = {post:post, offset:{stt: objElement.elvalue},pagesize:pagesize, element:{stt: "#" + element}, selected:getAllSelectedValues('#restriction_sku_selected')};
                }                 
                loadElement("#dummy-loader", 
                    "/dcms/template/" + method, 
                    "post", 
                    loadParam, 
                    null, 
                    MESSAGE_LOADING, 
                    'html',
                    "#"+element
                );
                offsetHash[objElement.elm] = objElement.elvalue + pagesize;
            }
        } else if(value == 'append-search-sku-usap-list') {
            $("#" + element +' option:selected').remove();           
            searchBox(
                'indirect',
                $('#restriction_sku_selector_sku_usap_search').val(), 
                "#dummy-loader", 
                method, 
                'RESTRICTION_SKU_SKU_USAP_LIST_SEARCH_OFFSET_SIZE', 
                'RESTRICTION_SKU_SKU_USAP_LIST_SEARCH', 
                'RESTRICTION_SKU_SKU_USAP_LIST_OFFSET_SIZE',
                '#restriction_sku_sku_usap_list',
                '#restriction_sku_selected',
                13,
                'restriction_sku_brand_list',
                'usap'
            );
        } else if(value == 'append-search-sku-jcw-list') {
            $("#" + element +' option:selected').remove();           
            searchBox(
                'indirect',
                $('#restriction_sku_selector_sku_jcw_search').val(), 
                "#dummy-loader", 
                method, 
                'RESTRICTION_SKU_SKU_JCW_LIST_SEARCH_OFFSET_SIZE', 
                'RESTRICTION_SKU_SKU_JCW_LIST_SEARCH', 
                'RESTRICTION_SKU_SKU_JCW_LIST_OFFSET_SIZE',
                '#restriction_sku_sku_jcw_list',
                '#restriction_sku_selected',
                13,
                'restriction_sku_brand_list',
                'jcw'
            );
        } else if(value == 'append-search-sku-stt-list') {
            $("#" + element +' option:selected').remove();           
            searchBox(
                'indirect',
                $('#restriction_sku_selector_sku_stt_search').val(), 
                "#dummy-loader", 
                method, 
                'RESTRICTION_SKU_SKU_STT_LIST_SEARCH_OFFSET_SIZE', 
                'RESTRICTION_SKU_SKU_STT_LIST_SEARCH', 
                'RESTRICTION_SKU_SKU_STT_LIST_OFFSET_SIZE',
                '#restriction_sku_sku_stt_list',
                '#restriction_sku_selected',
                13,
                'restriction_sku_brand_list',
                'stt'
            );
        } else {
            return false;
        }
    }
    
    function skuList(elementBrandId, valueBrand) {
        
        var value = trimValue(valueBrand);

        if(value == 'append') {
            
            var objElementSkuBrand = getObjectElementValue(offsetHash, 'RESTRICTION_SKU_BRAND_LIST_OFFSET_SIZE');
            if(objElementSkuBrand != false) {
                 $("#" + elementBrandId +' option:selected').remove();
                 loadElement("#dummy-loader", 
                    "/dcms/template/brandlist", 
                    "post", 
                    {offset:objElementSkuBrand.elvalue,pagesize:pagesize, element:"#" + elementBrandId, selected:getAllSelectedValues('#restriction_sku_selected')}, 
                    null, 
                    MESSAGE_LOADING, 
                    'html',
                    "#"+elementBrandId
                );
                offsetHash[objElementSkuBrand.elm] = objElementSkuBrand.elvalue + pagesize;
            }            
        } else if (value == 'append-search-sku-brand-list') {
            $("#" + elementBrandId +' option:selected').remove();
            searchBox(
                'indirect',
                $('#restriction_sku_selector_brand_search').val(), 
                "#dummy-loader", 
                'brandlist', 
                'RESTRICTION_SKU_BRAND_LIST_SEARCH_OFFSET_SIZE', 
                'RESTRICTION_SKU_BRAND_LIST_SEARCH', 
                'RESTRICTION_SKU_BRAND_LIST_OFFSET_SIZE',
                "#" + elementBrandId,
                '#restriction_sku_selected'
            );
        } else {
            
            var objElementSearchOffsetUsap = getObjectElementValue(offsetHash, 'RESTRICTION_SKU_SKU_USAP_LIST_SEARCH_OFFSET_SIZE');
                offsetHash[objElementSearchOffsetUsap.elm] = 0;
            var objElementSearchHashUsap = getObjectElementValue(searchHash, 'RESTRICTION_SKU_SKU_USAP_LIST_SEARCH');
                searchHash[objElementSearchHashUsap.elm] = "search";
            var objElementUsap = getObjectElementValue(offsetHash, 'RESTRICTION_SKU_SKU_USAP_LIST_OFFSET_SIZE');
                offsetHash[objElementUsap.elm] = 0;

            var objElementSearchOffsetJcw = getObjectElementValue(offsetHash, 'RESTRICTION_SKU_SKU_JCW_LIST_SEARCH_OFFSET_SIZE');
                offsetHash[objElementSearchOffsetJcw.elm] = 0;
            var objElementSearchHashJcw = getObjectElementValue(searchHash, 'RESTRICTION_SKU_SKU_JCW_LIST_SEARCH');
                searchHash[objElementSearchHashJcw.elm] = "search";
            var objElementJcw = getObjectElementValue(offsetHash, 'RESTRICTION_SKU_SKU_JCW_LIST_OFFSET_SIZE');
                offsetHash[objElementJcw.elm] = 0;
                
            var objElementSearchOffsetStt = getObjectElementValue(offsetHash, 'RESTRICTION_SKU_SKU_STT_LIST_SEARCH_OFFSET_SIZE');
                offsetHash[objElementSearchOffsetStt.elm] = 0;
            var objElementSearchHashStt = getObjectElementValue(searchHash, 'RESTRICTION_SKU_SKU_STT_LIST_SEARCH');
                searchHash[objElementSearchHashStt.elm] = "search";
            var objElementStt = getObjectElementValue(offsetHash, 'RESTRICTION_SKU_SKU_STT_LIST_OFFSET_SIZE');
                offsetHash[objElementStt.elm] = 0;               

            if(objElementUsap != false && objElementJcw != false && objElementStt != false) {
                $('#restriction_sku_sku_usap_list').empty();
                $('#restriction_sku_sku_jcw_list').empty();
                $('#restriction_sku_sku_stt_list').empty();
                
                loadElement("#dummy-loader", 
                    "/dcms/template/brandskulist", 
                    "post", 
                    {
                        offset:{usap:offsetHash[objElementUsap.elm], jcw:offsetHash[objElementJcw.elm], stt:offsetHash[objElementStt.elm]}, 
                        pagesize:pagesize, 
                        element:{usap:'#restriction_sku_sku_usap_list', jcw:'#restriction_sku_sku_jcw_list', stt:'#restriction_sku_sku_stt_list'},
                        selected:getAllSelectedValues('#restriction_sku_selected'),
                        post:value
                    },
                    null, 
                    MESSAGE_LOADING, 
                    'html',
                    "#"+elementBrandId
                );
                offsetHash[objElementUsap.elm] = pagesize;
                offsetHash[objElementJcw.elm] = pagesize;
                offsetHash[objElementStt.elm] = pagesize;
            }
            $('#restriction_sku_selector_sku_usap_search').val('');
            $('#restriction_sku_selector_sku_jcw_search').val('');
            $('#restriction_sku_selector_sku_stt_search').val('');

        }
        
    }
    
    function populateSelected() {
        
        $("#restriction_part_selected, #restriction_brand_selected, #restriction_brand_part_selected, #restriction_part_brand_selected, #restriction_sku_selected").find('option').each(function() {
            $(this).attr('selected', 'selected');
        });   
    }
    
</script>
                
                
                
                
                
                
                
                Status: <?php echo (isset($this->coupon['items']) && count($this->coupon['items']) > 0) ? "published" : "testing" ?>
                <?php
                if(isset($this->coupon['items']) && count($this->coupon['items']) > 0){
                    echo $this->partial('coupon/couponlist.phtml', $this); 
                }
                 
                 
                 ?>
                
                <div style="text-align: right;">
                    <div class="bg_btn">
                        <div style="float: left !important">
                            <div id="dummy-loader"></div>
                        </div>
                        <input type="button" value="Save" name="save_template" onclick="populateSelected();document.getElementById('Dcms_Template_Addedit').submit();" class="uniform" />
                        <input type="button" value="Cancel" name="cancel_template" onclick="location.href='/dcms/template'" class="uniform" />
                    </div>
                    <div style="clear: both;"></div>
                </div>
                <div style="clear: both;"></div>
            </form>
            <?php endif; ?>
                        <?php if(isset($this->success)) {
                                echo $this->success;
                            } 
                        ?>

        </div>
    </div>
</div>
