<style>
.bg_btn{
    background-color: #F6F6F6;
    border-bottom: 5px solid #555555;
    border-top: 5px solid #555555;
    margin-top: 20px;
    padding: 8px 10px;
    text-align: right;
}
</style>
<div class="container">
    <?php echo $this->partial('partials/tabs.phtml', $this); ?>
    <div class="tabbed-content content-tab">
        <div class="messages">
            <?php echo $this->flashMessages(); ?>
        </div>  
        <?php $pagevars = $this->paginator->getPages(); ?>
        <table width="100%" border="0" cellpadding="0" cellspacing="2" id="domainTable">
            <tr>
                <td colspan="2">
                    <div class="pagination">
                        <div class="page-info"><?php echo $pagevars->totalItemCount; ?></div>
                        <?php echo $this->paginationControl($this->paginator, 'Sliding', '/partials/couponownerpaginationcontrols.phtml', array('request' => $this->request)); ?>
                    </div>
                </td>
            </tr>
            <tr style="background-color:#FFEBCD;">
                <td><div style="padding:5px;"><b>Coupon Owner</b></div></td>
                <td width="100" style="text-align:center;"><div style="padding:5px;"><b>Action</b></div></td>
            </tr>

            <?php
            if (count($this->paginator)) {
                echo $this->partialLoop('partials/couponowner.listing.phtml', $this->paginator);
            }else{
                echo '<tr>
                    <td colspan="2"><center>No Owners available</center></td>
                </tr>
                <tr>
                    <td colspan="2">&nbsp;</td>
                </tr>';
            }
            ?>

            <tr>
                <td colspan="2">
                    <div class="pagination">
                        <div class="page-info"><?php echo $pagevars->totalItemCount; ?></div>
                        <?php echo $this->paginationControl($this->paginator, 'Sliding', '/partials/couponownerpaginationcontrols.phtml', array('request' => $this->request)); ?>
                    </div>
                </td>
            </tr>
        </table>
        <div class="bg_btn"><input type="button" value="Add New Coupon Owner" name="owner_add" onclick="location.href='/dcms/couponowners/addowner';" class="uniform" /></div>
    </div>
</div>