<script>
    function toggleCheckbox(chk, checkboxes)
    {
        if(!chk.checked){
            for (i = 0; i < checkboxes.length; i++){
                checkboxes[i].checked = false ;
                //                $("#couponContainer option").remove();
            }
        }else{
            for (i = 0; i < checkboxes.length; i++){
                checkboxes[i].checked = true ;
                //                var val = checkboxes[i].getAttribute('name');
                //                if($('#couponContainer option[value="'+val+'"]').length == 0){
                //                    $("#couponContainer").append($('<option></option>').val(val).html(val));
                //                }
                
            }
        }
        
    }
    
    function toggleDeleteList(checkedItem){
        var val = checkedItem.getAttribute('name');
        if(!checkedItem.checked){
            if($('#couponContainer option[value="'+val+'"]').length > 0){
                $('#couponContainer option[value="'+val+'"]').remove();
            }
        }else{
            if($('#couponContainer option[value="'+val+'"]').length == 0){
                $("#couponContainer").append($('<option></option>').val(val).html(val));
            }
        }
    }
    
    function popView(link, windowName) {
    
        var params;
        params = 'width='+screen.width;
        params += ', height='+screen.height;
        params += ', top=0, left=0';
        params += ', fullscreen=yes, scrollbars=yes';
    
        window.open(link.href, windowName, params);
        return false;
    }
    
    function deleteCoupons(){
        var counter = 0;
        var checkboxes = document.homedelete.checkone;
        if(checkboxes.length != undefined){
            for (i = 0; i < checkboxes.length; i++){
                if(checkboxes[i].checked) counter++;
            }
        }else{
            if(document.getElementById("checkone").checked == true) counter++;
        }
        if(counter>0){
            var answer = confirm("Are you sure you want to delete selected item/s?");
            if (answer){
                return true;
            }
            else{
                return false;
            }
        }
        
        
        
    }
</script>
<?php
//$key = rand(0, 9999);
//for popview
//$this->headScript()->appendFile("/assets/js/jquery/functions.js?q=" . $key);
?>
<div class="container">
    <?php echo $this->partial('partials/tabs.phtml', $this); ?>
    <div class="tabbed-content content-tab">
        <!--        <form name="home" enctype="application/x-www-form-urlencoded" method="post">-->
        <div class="messages"> 
            <?php echo $this->flashMessages(); ?> 
        </div> 

        <div id="main">
            <?php
            $coupon_code = $this->form->getElement('coupon_code');
            $coupon_site = $this->form->getElement('coupon_domains');
            $expiration_type = $this->form->getElement('expiration_type');
            $publish_checkbox = $this->form->getElement('status');
            $counPerPage = $this->form->getElement('countperpage');
            ?>
            <div class="coupons-navi">
                <form name="home" enctype="application/x-www-form-urlencoded" method="post">
                    <table border="0">
                        <tbody>
                            <tr>
                                <td width="20%"><b><?php echo $coupon_code->getLabel(); ?></b></td>
                                <td width="20%">
                                    <?php
                                    isset($this->query['coupon.code']) ? $coupon_code->setValue($this->query['coupon.code']) : "";
                                    echo $coupon_code;
                                    ?>

                                </td>
                                <td width="20%">&nbsp;</td>
                                <td width="20%">
                                    <b><?php
                                    isset($this->query['status']) ? $publish_checkbox->setValue(($this->query['status']=='published') ? true : false) : "";
                                    echo $publish_checkbox->getLabel();
                                    ?></b> <?php echo $publish_checkbox ?>
                                </td>
                                <td width="20%">
                                    &nbsp;
                                </td>
                            </tr>
                            <tr>
                                <td><b><?php echo $coupon_site->getLabel(); ?></b></td>
                                <td>
                                    <span style="font-size: 12px; font-weight: 500;">
                                        <?php
                                        isset($this->query['coupon.domains']) ? $coupon_site->setValue($this->query['coupon.domains']) : "";
                                        echo $coupon_site;
                                        ?>
                                    </span>
                                </td>

                                <td><b><?php echo $expiration_type->getLabel(); ?></b></td>
                                <td><span style="font-size: 12px; font-weight: 500;">
                                        <?php
                                        isset($this->query['expiration.type']) ? $expiration_type->setValue($this->query['expiration.type']) : "";
                                        echo $expiration_type;
                                        ?>
                                    </span></td>
                                <td width="5%"><span style="color: black; font-size: 10px; font-weight: 700;"></span></td>
                            </tr>
                            <tr>
                                <td colspan="5">
                                    <?php
                                    isset($this->countperpage) ? $counPerPage->setValue($this->countperpage) : "";
                                    $counPerPage->setDecorators(array('ViewHelper'));
                                    echo $counPerPage->getLabel();
                                    ?>
                                    <?php echo $counPerPage; ?>
                                </td>
                            </tr>
                        </tbody>

                    </table>

                </form>
                <div style="color: blue; font-size: 14px; font-weight: 400;"></div>
                <div class="results-no"><!-- 1-10 results out of 1,837 --></div>    
            </div>
            <br>
            <div id="search"></div>
        </div>
        <div>
            <?php $pagevars = $this->paginator->getPages(); ?>
            <div class="pagination">
                <div class="page-info">
                    <?php echo $pagevars->totalItemCount; ?>
                </div>

                <?php
                echo $this->paginationControl($this->paginator, 'Sliding', '/partials/paginationcontrols.phtml', array('request' => $this->request));
                ?>
            </div>
            <form name="homedelete" enctype="application/x-www-form-urlencoded" method="post" action="<?php echo $this->deleteForm->getAction(); ?>">
                <?php
//                $couponContainer = $this->form->getElement('couponContainer');
//                echo $couponContainer;
                ?>
                <?php $this->sort = ($this->sort == "1") ? "-1": "1"; ?>
                <table  class="datatable" width="100%">
                    <thead>
                        <tr>
                            <td colspan="7">
                                <!--<img src="/assets/img/delete.png" onclick="document.homedelete.submit();">-->
                                
                                <input type="submit" value="Delete" onclick="return deleteCoupons();">

                            </td>
                        </tr>
                        <tr style="text-align: left;">
                            <th width="2%" rowspan="2">
							<?php
                                echo $this->deleteForm->getElement('checkall');
                                ?>
                            </th>
                            <th width="20%">
                                <a href="<?php echo $this->url(array_merge($this->request, array('sortby' => "coupon.code", 'sort' => $this->sort)), 'default'); ?>">
                                    Coupon Name
                                </a>
                            </th>
                            <th  width="10%">
                                <a href="<?php echo $this->url(array_merge($this->request, array('sortby' => "createdAt", 'sort' => $this->sort)), 'default'); ?>">
                                    Date Created
                                </a></th>
                            <th  width="10%">Template</th>
                            <th  width="5%">
                                <a href="<?php echo $this->url(array_merge($this->request, array('sortby' => "coupon.domains", 'sort' => $this->sort)), 'default'); ?>">
                                    Site
                                </a>
                            </th>
                            <th  width="20%">Time Frame</th>
                            <th  width="5%">
                                <a href="<?php echo $this->url(array_merge($this->request, array('sortby' => "coupon.owner", 'sort' => $this->sort)), 'default'); ?>">
                                    Owner
                                </a>
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        if (count($this->paginator)) {
                            echo $this->partialLoop('partials/coupon.listing.phtml', $this->paginator);
                        }
                        ?>
                    </tbody>
                    <tfoot>
                    </tfoot>
                </table>
            </form>
            <div class="pagination">
                <div class="page-info">
                    <?php echo $pagevars->totalItemCount; ?>
                </div>

                <?php
                echo $this->paginationControl($this->paginator, 'Sliding', '/partials/paginationcontrols.phtml', array('request' => $this->request));
                ?>
            </div>

        </div>
        <!--        </form>-->
    </div>

</div>

