
<?php $__row_style = (($this->partialCounter % 2 )? "dark" : "light"); ?>
           <tr class="<?php echo $__row_style;?>">
                <td><?php echo $this->username;?></td>
                <td><?php echo $this->role_id;?></td>
                <td><a href="/user/admin/delusername/id/<?php echo $this->username;?>/page/<?php echo $this->current; ?>" onclick="return confirm('Are you sure you want to delete this user');">Delete</a></td>
            </tr>