<div class="container">
    <?php echo $this->partial('partials/tabs.phtml', $this); ?>
    <div class="tabbed-content content-tab">
        <div class="messages"> 
            <?php echo $this->flashMessages(); ?> 
        </div> 
        <div>


           
                    <?php echo $this->partial('partials/otucoupon.status.phtml', $this); ?>
                


        </div>
        <!--        </form>-->
    </div>

</div>

